Food_Waste_ManagementSystem/urls.py
from django.contrib import admin
from django.urls import path
from foodwaste.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('food_Available', food_Available, name='food_Available'),
    path('checkFoodAvailable/<int:pid>', checkFoodAvailable, name='checkFoodAvailable'),
    path('contact/', contact, name='contact'),
    path('donor_login',donor_login, name='donor_login'),
    path('signup', signup, name='signup'),
    path('admin_login', admin_login, name='admin_login'),

    path('dashboard', dashboard, name='dashboard'),
    path('addState', addState, name='addState'),
    path('manageState', manageState, name='manageState'),
    path('editState<int:pid>', editState, name='editState'),
    path('deleteState<int:pid>', deleteState, name='deleteState'),
    path('addCity', addCity, name='addCity'),
    path('manageCity', manageCity, name='manageCity'),
    path('editCity<int:pid>', editCity, name='editCity'),
    path('deleteCity<int:pid>', deleteCity, name='deleteCity'),
    path('regFoodDonor', regFoodDonor, name='regFoodDonor'),
    path('deleteDonor<int:pid>', deleteDonor, name='deleteDonor'),
    path('listedFood', listedFood, name='listedFood'),
    path('foodDetails<int:pid>', foodDetails, name='foodDetails'),
    path('newRequest', newRequest, name='newRequest'),
    path('completeRequest', completeRequest, name='completeRequest'),
    path('rejectRequest', rejectRequest, name='rejectRequest'),
    path('allRequest', allRequest, name='allRequest'),
    path('view_requestDtls<int:pid>', view_requestDtls, name='view_requestDtls'),
    path('unreadEnquiry', unreadEnquiry, name='unreadEnquiry'),
    path('readEnquiry', readEnquiry, name='readEnquiry'),
    path('viewEnquiry<int:pid>', viewEnquiry, name='viewEnquiry'),
    path('reportDonatedFood', reportDonatedFood, name='reportDonatedFood'),
    path('reportregfoodDonor', reportregfoodDonor, name='reportregfoodDonor'),
    path('searchFood', searchFood, name='searchFood'),
    path('changePassword', changePassword, name='changePassword'),
    path('logout/', Logout, name='logout'),

    path('donorDashboard', donorDashboard, name='donorDashboard'),
    path('addFood', addFood, name='addFood'),
    path('manageFood', manageFood, name='manageFood'),
    path('editFood<int:pid>', editFood, name='editFood'),
    path('deleteFood<int:pid>', deleteFood, name='deleteFood'),
    path('load_city',load_city, name="ajax_load_city"),
    path('donorNewRequest', donorNewRequest, name='donorNewRequest'),
    path('donorCompletedRequest', donorCompletedRequest, name='donorCompletedRequest'),
    path('donorRejectRequest', donorRejectRequest, name='donorRejectRequest'),
    path('donorAllRequest', donorAllRequest, name='donorAllRequest'),
    path('viewRequestDetails<int:pid>', viewRequestDetails, name='viewRequestDetails'),
    path('deleteRequest<int:pid>', deleteRequest, name='deleteRequest'),
    path('donorSearch', donorSearch, name='donorSearch'),
    path('profile', profile, name='profile'),
    path('donorChangePassword', donorChangePassword, name='donorChangePassword'),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

foodwaste/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class State(models.Model):
    StateName = models.CharField(max_length=100, null=True)
    RegDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.StateName

class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE, null=True)
    CityName = models.CharField(max_length=100, null=True)
    CreationDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.CityName

class Contact(models.Model):
    fullName = models.CharField(max_length=150, null=True)
    Email = models.CharField(max_length=100, null=True)
    Phone = models.CharField(max_length=15, null=True)
    Message = models.CharField(max_length=250, null=True)
    EnquiryDate = models.DateTimeField(auto_now_add=True)
    IsRead = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.fullName

class Donor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    MobileNumber = models.CharField(max_length=100, null=True)
    RegDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name

class Food(models.Model):
    donorid = models.ForeignKey(Donor, on_delete=models.CASCADE, null=True)
    foodId = models.CharField(max_length=150, null=True)
    FoodItems = models.CharField(max_length=250, null=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    Description = models.CharField(max_length=300, null=True)
    PickupDate = models.DateField(null=True)
    PickupAddress = models.CharField(max_length=250, null=True)
    ContactPerson = models.CharField(max_length=150, null=True)
    CPMobNumber = models.CharField(max_length=15, null=True)
    Image = models.FileField(null=True,blank=True)
    CreationDate = models.DateTimeField(auto_now_add=True)
    UpdationDate = models.DateField(null=True)

    def __str__(self):
        return self.foodId

class Foodrequests(models.Model):
    food = models.ForeignKey(Food, on_delete=models.CASCADE, null=True)
    requestNumber = models.CharField(max_length=150, null=True)
    fullName = models.CharField(max_length=250, null=True)
    mobileNumber = models.CharField(max_length=15, null=True)
    message = models.CharField(max_length=350, null=True)
    requestDate = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, null=True)
    donorRemark = models.CharField(max_length=250, null=True)
    requestCompletionDate = models.DateField(null=True)

    def __str__(self):
        return self.fullName

foodwaste/views.py
import random

from django.contrib.auth import authenticate, logout, login
from django.db.models import Q
from django.shortcuts import render, redirect
from datetime import date
from .models import *

# Create your views here.

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def food_Available(request):
    food = Food.objects.all()
    return render(request, 'food_Available.html', locals())

def checkFoodAvailable(request,pid):
    food = Food.objects.get(id=pid)
    foodid = food.id

    if request.method == "POST":
        fullName = request.POST['fullName']
        mobileNumber = request.POST['mobileNumber']
        message = request.POST['message']
        requestNumber = str(random.randint(10000000, 99999999))
        try:
            Foodrequests.objects.create(food=food, fullName=fullName, mobileNumber=mobileNumber, message=message,
                                   requestNumber=requestNumber)
            error = "no"
        except:
            error = "yes"
    return render(request, 'checkFoodAvailable.html', locals())

def contact(request):
    error = ""
    if request.method == "POST":
        fullName = request.POST['fullName']
        Email = request.POST['Email']
        Phone = request.POST['Phone']
        Message = request.POST['Message']

        try:
            Contact.objects.create(fullName=fullName, Email=Email, Phone=Phone, Message=Message)
            error = "no"
        except:
            error = "yes"
    return render(request, 'contact.html', locals())

def donor_login(request):
    error = ""
    if request.method == 'POST':
        e = request.POST['emailid']
        p = request.POST['password']
        user = authenticate(username=e, password=p)
        try:
            if user:
                login(request, user)
                error = "no"
            else:
                error = "yes"
        except:
            error = "yes"
    return render(request, 'donor_login.html', locals())

def signup(request):
    error = ""
    if request.method == "POST":
        fname = request.POST['firstName']
        lname = request.POST['lastName']
        MobileNumber = request.POST['MobileNumber']
        email = request.POST['Email']
        password = request.POST['Password']

        try:
            user = User.objects.create_user(username=email, password=password, first_name=fname, last_name=lname)
            Donor.objects.create(user=user, MobileNumber=MobileNumber)
            error = "no"
        except:
            error = "yes"
    return render(request, 'signup.html', locals())

def admin_login(request):
    error = ""
    if request.method == 'POST':
        u = request.POST['uname']
        p = request.POST['password']
        user = authenticate(username=u, password=p)
        try:
            if user.is_staff:
                login(request, user)
                error = "no"
            else:
                error = "yes"
        except:
            error = "yes"
    return render(request, 'admin_login.html', locals())

def dashboard(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    totalstate = State.objects.all().count()
    totalcity = City.objects.all().count()
    totaldonor = Donor.objects.all().count()
    totalfood = Food.objects.all().count()
    totalrequest = Foodrequests.objects.all().count()
    totalnewrequest = Foodrequests.objects.filter(status=None).count()
    totalrejectrequest = Foodrequests.objects.filter(status='Request Rejected').count()
    totalcompleterequest = Foodrequests.objects.filter(status='Food Take Away/ Request Completed').count()
    return render(request, 'admin/dashboard.html', locals())

def addState(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    error = ""
    if request.method == "POST":
        StateName = request.POST['StateName']

        try:
            State.objects.create(StateName=StateName)
            error = "no"
        except:
            error = "yes"
    return render(request, 'admin/addState.html', locals())

def manageState(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    state = State.objects.all()
    return render(request, 'admin/manageState.html', locals())

def editState(request,pid):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    error = ""
    state = State.objects.get(id=pid)
    if request.method == "POST":
        StateName = request.POST['StateName']

        state.StateName = StateName
        try:
            state.save()
            error = "no"
        except:
            error = "yes"
    return render(request, 'admin/editState.html', locals())

def deleteState(request, pid):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    state = State.objects.get(id=pid)
    state.delete()
    return redirect('manageState')

def addCity(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    state = State.objects.all()
    if request.method == "POST":
        sid = request.POST['state']
        stateid = State.objects.get(id=sid)

        cityname = request.POST['CityName']

        try:
            City.objects.create(state=stateid, CityName=cityname)
            error = "no"
        except:
            error = "yes"
    return render(request, 'admin/addCity.html', locals())

def manageCity(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    city = City.objects.all()
    return render(request, 'admin/manageCity.html', locals())

def editCity(request,pid):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    error = ""
    state = State.objects.all()
    city = City.objects.get(id=pid)
    if request.method == "POST":
        sid = request.POST['state']
        state1 = State.objects.get(id=sid)
        cityname = request.POST['CityName']

        city.state = state1
        city.CityName = cityname

        try:
            city.save()
            error = "no"
        except:
            error = "yes"
    return render(request, 'admin/editCity.html', locals())

def deleteCity(request, pid):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    city = City.objects.get(id=pid)
    city.delete()
    return redirect('manageCity')

def regFoodDonor(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    donor = Donor.objects.all()
    return render(request, 'admin/regFoodDonor.html', locals())

def deleteDonor(request,pid):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    donor = Donor.objects.get(id=pid)
    donor.delete()
    return redirect('regFoodDonor')

def listedFood(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    food = Food.objects.all()
    return render(request, 'admin/listedFood.html', locals())

def foodDetails(request,pid):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    food = Food.objects.get(id=pid)
    return render(request, 'admin/foodDetails.html', locals())

def newRequest(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    foodrequest = Foodrequests.objects.filter(status__isnull=True)
    return render(request, 'admin/newRequest.html', locals())

def completeRequest(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    foodrequest = Foodrequests.objects.filter(status='Food Take Away/ Request Completed')
    return render(request, 'admin/completeRequest.html', locals())

def rejectRequest(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    foodrequest = Foodrequests.objects.filter(status='Request Rejected')
    return render(request, 'admin/rejectRequest.html', locals())

def allRequest(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    foodrequest = Foodrequests.objects.all()
    return render(request, 'admin/allRequest.html', locals())

def view_requestDtls(request,pid):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    foodrequest = Foodrequests.objects.get(id=pid)
    return render(request, 'admin/view_requestDtls.html', locals())

def unreadEnquiry(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    contact = Contact.objects.filter(IsRead__isnull=True)
    return render(request, 'admin/unreadEnquiry.html', locals())

def readEnquiry(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    contact = Contact.objects.filter(IsRead='yes')
    return render(request, 'admin/readEnquiry.html', locals())

def viewEnquiry(request,pid):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    contact = Contact.objects.get(id=pid)
    contact.IsRead = "yes"
    contact.save()
    return render(request, 'admin/viewEnquiry.html', locals())

def reportDonatedFood(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    if request.method == "POST":
        fd = request.POST['fromDate']
        td = request.POST['toDate']
        food = Food.objects.filter(Q(CreationDate__gte=fd) & Q(CreationDate__lte=td))
        return render(request, 'admin/reportdonatedbtwdates.html', locals())
    return render(request, 'admin/reportDonatedFood.html')

def reportregfoodDonor(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    if request.method == "POST":
        fd = request.POST['fromDate']
        td = request.POST['toDate']
        donor = Donor.objects.filter(Q(RegDate__gte=fd) & Q(RegDate__lte=td))

foodwaste/templates/about.html
{% extends 'navbar.html' %}
{% block main %}
{% load static %}

<!-- Page Header Start -->
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>About Us</h2>
            </div>
            <div class="col-12">
                <a href="{% url 'index' %}">Home</a>
                <a href="{% url 'about' %}">About Us</a>
            </div>
        </div>
    </div>
</div>
<!-- Page Header End -->


<!-- About Start -->
<div class="about">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="about-img" data-parallax="scroll" data-image-src="{% static 'img/about.jpg' %}"></div>
            </div>
            <div class="col-lg-6">
                <div class="section-header">
                    <p>Learn About Us</p>
                    <h2>All About Food Donate</h2>
                </div>
                <div class="about-tab">
                    <ul class="nav nav-pills nav-justified">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="pill" href="#tab-content-1">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab-content-2">Mission</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab-content-3">Vision</a>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <div id="tab-content-1" class="container tab-pane active">
                            The problem of food waste is a relatively modern one. India is an ancient civilisation and
                            we have been prudent about food for millennia. Our parents and grandparents, too, once
                            approached food and cooking with the same prudence. Yet, somewhere along the way, we lost
                            sight of this “waste not, want not” mentality.
                        </div>
                        <div id="tab-content-2" class="container tab-pane fade">
                            There is also a significant amount of food waste generated in our homes. As per the Food
                            Waste Index Report 2021, a staggering 50 kg of food is thrown away per person every year in
                            Indian homes. This excess food waste usually ends up in landfills, creating potent
                            greenhouse gases which have dire environmental implications. Meanwhile, we continue to be
                            greenwashed into amassing more “organic” and “sustainable” products than we really need.
                        </div>
                        <div id="tab-content-3" class="container tab-pane fade">
                            This has been a problem for decades, and is worsening with time. It was only when the
                            COVID-19 pandemic came along in 2020 that many of us began taking note. Affluent Indians
                            were suddenly inconvenienced by things otherwise taken for granted, like procuring groceries
                            or worrying about how long their supplies would last. We came to realise that the food we
                            eat goes far beyond the few bites it takes for us to finish it.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->


<!-- Facts Start -->
<div class="facts" data-parallax="scroll" data-image-src="{% static 'img/facts.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="facts-item">
                    <i class="flaticon-home"></i>
                    <div class="facts-text">
                        <h3 class="facts-plus" data-toggle="counter-up">150</h3>
                        <p>Countries</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="facts-item">
                    <i class="flaticon-charity"></i>
                    <div class="facts-text">
                        <h3 class="facts-plus" data-toggle="counter-up">400</h3>
                        <p>Volunteers</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="facts-item">
                    <i class="flaticon-kindness"></i>
                    <div class="facts-text">
                        <h3 class="facts-dollar" data-toggle="counter-up">10000</h3>
                        <p>Our Goal</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="facts-item">
                    <i class="flaticon-donation"></i>
                    <div class="facts-text">
                        <h3 class="facts-dollar" data-toggle="counter-up">5000</h3>
                        <p>Raised</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Facts End -->


<!-- Team Start -->
<div class="team">
    <div class="container">
        <div class="section-header text-center">
            <p>Meet Our Team</p>
            <h2>Awesome guys behind our charity activities</h2>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="team-item">
                    <div class="team-img">
                        <img src="{% static 'img/team-1.png' %}" alt="Team Image">
                        <!-- <img src="img/te" alt=""> -->
                    </div>
                    <div class="team-text">
                        <h2>Ayush Prajapati</h2>
                        <p>Founder & CEO</p>
                        <div class="team-social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="team-item">
                    <div class="team-img">
                        <img src="{% static 'img/sandipta.jpg' %}" alt="Team Image">
                    </div>
                    <div class="team-text">
                        <h2>Sandipta</h2>
                        <p>Chef Executive</p>
                        <div class="team-social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="team-item">
                    <div class="team-img">
                        <img src="{% static 'img/manjit.png' %}" alt="Team Image">
                    </div>
                    <div class="team-text">
                        <h2>Manjit </h2>
                        <p>Chef Advisor</p>
                        <div class="team-social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="team-item">
                    <div class="team-img">
                        <img src="{% static 'img/payal.jpg' %}" alt="Team Image">
                    </div>
                    <div class="team-text">
                        <h2>Payal</h2>
                        <p>Advisor</p>
                        <div class="team-social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Team End -->

{% endblock %}

foodwaste/templates/checkFoodAvailable.html
{% extends 'navbar.html' %}
{% block main %}
{% load static %}

<!-- Page Header Start -->
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>Food Details</h2>
            </div>
            <div class="col-12">
                <a href="{% url 'index' %}">Home</a>
                <a href="">Food Details</a>
            </div>
        </div>
    </div>
</div>
<!-- Page Header End -->

<!-- Signup Start -->
<div class="food">
    <div class="container">
        <div class="section-header text-center">
            <h2>Food Details</h2>
        </div>
        <div class="food-img">
            <img src="{% static 'img/contact.jpg' %}" alt="Image">
        </div>
        <div class="food-form" style="width: 100%">
            <div id="success"></div>
            <table id="example" class="table table-bordered" style="width: 100%">
                <tr>
                    <th>Register By</th>
                    <td>{{food.donorid.user.first_name}} {{food.donorid.user.last_name}}</td>

                    <th>Registred Mobile Number</th>
                    <td>{{food.donorid.MobileNumber}}</td>
                </tr>

                <tr>
                    <th>Registred Email</th>
                    <td>{{food.donorid.user.username}}</td>

                    <th>Contact Person</th>
                    <td>{{food.ContactPerson}}</td>
                </tr>

                <tr>
                    <th>Contact Person Mobile Number</th>
                    <td>{{food.CPMobNumber}}</td>

                    <th>State Name</th>
                    <td>{{food.city.state.StateName}}</td>
                </tr>

                <tr>
                    <th>City Name</th>
                    <td>{{food.city.CityName}}</td>

                    <th>Description</th>
                    <td>{{food.Description}}</td>
                </tr>

                <tr>
                    <th>Pick Up Date</th>
                    <td>{{food.PickupDate}}</td>

                    <th>Pick Up Address</th>
                    <td>{{food.PickupAddress}}</td>
                </tr>

                <tr>
                    <th>Image</th>
                    <td><img src="{{food.Image.url}}" style="width: 100%; height: 150px;"></td>

                    <th>Status</th>
                    {% if food.foodrequests_set.all.0.status == None%}
                    <td>Not Update Yet</td>
                    {% else %}
                    <td>{{food.foodrequests_set.all.0.status}}</td>
                    {% endif %}
                </tr>

                {% if food.foodrequests_set.all.0.status == None%}
                <tr>
                    <td colspan="4">
                        <center>
                            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal"
                                    data-target="#myModal">Request Food
                            </button>
                        </center>
                    </td>
                </tr>
                {% endif %}
            </table>
        </div>

        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Food Request</h4>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="modal-body">
                            <p><input type="text" name="fullName" class="form-control" placeholder="Enter Full Name"
                                      required></p>
                            <p style="margin-top:1%"><input type="text" name="mobileNumber" class="form-control"
                                                            placeholder="Enter Mobile Number" maxlength="10" required>
                            </p>
                            <p style="margin-top:1%"><textarea name="message" class="form-control"
                                                               placeholder="Message if any" required></textarea></p>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- Signup End -->

{% if error == "no" %}
<script>
    alert('Request Successfully Sent. Your Request Number is {{requestNumber}}');
    window.location=('{% url 'food_Available' %}');

</script>
{% endif %}

{% if error == "yes" %}
<script>
    alert('Something went wrong. Try Again...');

</script>
{% endif %}


{% endblock %}